[package]
name = "uff-relax"
version = "1.0.0"
edition = "2024"
license = "MIT OR Apache-2.0"

[dependencies]
glam = { version = "0.31.0", features = ["serde"] }
rayon = "1.11.0"
serde = { version = "1.0.228", features = ["derive"] }
